### ISSUE TITLE
Retry should use backoff and warn about GitHub throttling

### ISSUE THREAD

**Issue by zifeo** [metatypedev/ghjk#20]
https://github.com/metatypedev/ghjk/actions/runs/7241178757/job/19724988848?pr=17

Use a token to bypass the throttling?

**Comment by Yohe-Am** [comment]
> token
Oh, yeah. Going to tackle that as part of #7.

**Comment by Yohe-Am** [comment]
Update: we're now using github tokens almost all the places we're using their API but it's far from ideal. 

1. For now, manual plumbing is required everywhere (same for backoff). Not only passing the headers but reading the env var during serialization in the port `conf` fn.
2. A bigger issue is that the ghjk model requires that all inputs have to go through serialization and this means that the sensitive token will go into the `lock.json`. Dev machines rarely run into rate limits but the `GITHUB_TOKEN` var might be set for some other reason which will mean it'll leak. I considered postponing this feature until a better solution is found but the ratelimits are a big issue.

A possible solution for the first issue is a dedicated `githubFetch` wrapper that might help port impls  from not forgetting to add the headers.

A possible solution for the second issue is making the section of code that extracts the `GITHUB_TOKEN` env var pause for a prompt unless some other flag/var is set.

Wdyt @zifeo ?

**Comment by zifeo** [comment]
@Yohe-Am I would go for the dedicated githubFetch that can add the header when needed. This way we can also make sure that only allowlisted env var end up in the plan 👍
