### ISSUE TITLE
Share port installs and downloads across environments

### ISSUE THREAD

**Issue by Yohe-Am** [metatypedev/ghjk#8]
If env `A` installs version `V` of port `P`, we want to avoid installing the same version of the same port for env `B` if the already existing install meets its needs. Some thoughts:

- Since ports are able to specify extra custom config for their installs, we dedupe not just on the version string but the entire InstallConfig (or it's hash)
  - Lockfiles are a pre-requisite for this
- Explore other avenues to improve port determinism
  - Consider restricting network access from all but the download steps
    - Asdf-compat will be special cased
  - ~~Consider replacing the procedural download step with one that just emits a list of URLs to download~~
    - ~~Asdf-compat will be special cased~~
    - Abandoning this as this gets in the way of using `git clone` or `aria2c magnet://sha256` to get source files. There were helpers added for simply downloading a list of URLs on the other hand.
  - [Nix Flakes](https://www.tweag.io/blog/2020-05-25-flakes/) have some great ideas around tese.

**Comment by zifeo** [comment]
This could include also the deno binary itself to run ghjk.

**Comment by Yohe-Am** [comment]
> deno binary

With the current setup, you only need to install ghjk (and deno) once on a system. It'll pick up an env as long as there's a `ghjk.ts` file to be found.

**Comment by zifeo** [comment]
@Yohe-Am I was a bit short on the message (from the phone). If the folder `installs` already vendors all the ports, we might install our version of deno already vendor at the correct place?

**Comment by Yohe-Am** [comment]
Ah, I see. Yeah, good idea. We'll want a port for `deno` anyways since the version one install for `ghjk` is not exposed to the rest of the system and envs that use it will have to explicitly `install` it. Adding a way to dedup that with the version used by ghjk itself will be great.
